[WIP] Create a developer mode command to ease development
mozilla-rally/rally-core-addon pull request #295
Opened 2021-01-12 16:57 UTC by Dexterp37

This introduces a 'watch' command. The command uses rollup to watch for UI and addon changes, updates the packed files, and makes sure web-ext picks up the changes. This fixes #3.

Checklist for reviewer:

- [ ] The description should reference a bug or github issue, if relevant.
- [ ] There must be a [`CHANGELOG.md`](./CHANGELOG.md) entry for any non-test change.
- [ ] Any change to the NPM commands must be carefully reviewed to make sure it won't break the Add-ons pipeline.
- [ ] Any version increase must follow the [release process](./docs/RELEASE_PROCESS.md).

2021-01-12 17:52 UTC, Dexterp37 commented
Unfortunately, the approach above doesn't work due to mozilla/web-ext#2122

2021-01-13 15:53 UTC, rpl commented
> Unfortunately, the approach above doesn't work due to [mozilla/web-ext#2122](https://github.com/mozilla/web-ext/issues/2122)

@Dexterp37 I just closed mozilla/web-ext#2122, but only because it was a duplicate of mozilla/web-ext#2104, it is a valid issue and (as we agreed in our triage meeting today) supporting `--watch-file` used more than ones is our preferred approach to fix that issue (instead of just improving the error message).

2021-03-16 16:42 UTC, rhelmer requested changes
I noticed that this is printed on the console:


```
  Your application is ready~! 🚀

  - Local:      http://localhost:5000
  - Network:    Add `--host` to expose
```

However that link doesn't work since this page is not in `moz-extension://`, so the polyfill library throws:
```
Uncaught Error: This script should only be loaded in a browser extension.
```

Related is that Svelte does not auto-reload the UI when loaded in `moz-extension://`, presumably because the `livereloadscript` thing it injects into the bundle doesn't work here.

So I'd ask that we suppress that message about the `localhost` server being ready, because that will just confuse new developers.

I *think* that it might be possible to make livereload actually work in extension context, but this feels unimportant compared to the overall greatness of this change :) Something to look into in the future maybe.

2021-03-16 16:43 UTC, rhelmer commented
> Related is that Svelte does not auto-reload the UI when loaded in `moz-extension://`, presumably because the `livereloadscript` thing it injects into the bundle doesn't work here.

Ah yeah this happens when it tries in `moz-extension://`:

```
Loading failed for the <script> with source “moz-extension://d32eeb5a-8ad4-2c47-91f5-b65a7f45ee9d:35729/livereload.js?snipver=1”.
```

2021-03-16 16:48 UTC, rhelmer commented
> Unfortunately, if the rally control panel (addon options page) is open, that specific page does not get refreshed. User must refresh it manually or close/reopen that tab. That's due to a [bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1667143).

Hm, are you certain this is the cause? If it were that bug, I'd think that the options page would close out from under you. I think the add-on being loaded as temporary by `web-ext` is avoiding that bug actually and lack odf auto-refresh is https://github.com/mozilla-rally/rally-core-addon/pull/295#issuecomment-800426951

However as I said in the review comment I am totally down with deferring all of this until later :)

2021-03-16 16:53 UTC, Dexterp37 commented
> Related is that Svelte does not auto-reload the UI when loaded in `moz-extension://`, presumably because the `livereloadscript` thing it injects into the bundle doesn't work here.

Yep, I'm aware that isn't working. If it weren't for the bug mentioned in the PR description, it would still work: web-ext reloads the extension, but Firefox is not closing the option window and re-opening it (it should do that).

2021-03-16 16:54 UTC, rhelmer commented
> > Related is that Svelte does not auto-reload the UI when loaded in `moz-extension://`, presumably because the `livereloadscript` thing it injects into the bundle doesn't work here.
> 
> Yep, I'm aware that isn't working. If it weren't for the bug mentioned in the PR description, it would still work: web-ext reloads the extension, but Firefox is not closing the option window and re-opening it (it should do that).

Would you mind splitting this out to a separate issue? It needn't block this one :)

2021-03-16 17:39 UTC, Dexterp37 commented
> 
> 
> > > Related is that Svelte does not auto-reload the UI when loaded in `moz-extension://`, presumably because the `livereloadscript` thing it injects into the bundle doesn't work here.
> > 
> > 
> > Yep, I'm aware that isn't working. If it weren't for the bug mentioned in the PR description, it would still work: web-ext reloads the extension, but Firefox is not closing the option window and re-opening it (it should do that).
> 
> Would you mind splitting this out to a separate issue? It needn't block this one :)

Filed https://github.com/mozilla-rally/rally-core-addon/issues/498

2021-03-16 17:40 UTC, rhelmer approved these changes

2021-03-16 17:41 UTC, merged