Update code to ES6
mozilla-rally/rally-core-addon pull request #421
Opened 2021-02-19 02:47 UTC by Sarthak-Dayal

Update some code to ES6 to address #416 .

Specifically,

- [X] Replaced all require statements with imports
- [X] Changed var to let keywords

This helps ensure that all of the code is up to date with ES6 standards and allows for easier code maintenance.

Checklist for reviewer:

- [ ] The description should reference a bug or github issue, if relevant.
- [ ] There must be a [`CHANGELOG.md`](./CHANGELOG.md) entry for any non-test change.
- [ ] Any change to the NPM commands must be carefully reviewed to make sure it won't break the Add-ons pipeline.
- [ ] Any version increase must follow the [release process](./docs/RELEASE_PROCESS.md).

2021-02-19 10:01 UTC, Dexterp37 requested changes
Thank you for your contribution, @Sarthak-Dayal!

This looks good overall, there's a few minor changes requested (see my comments), and two main things that we need to change in order to make tests work.

1. Due to how ES6 `import` support works in MochaJS, we need to rename our unit test files to have the `mjs` extension instead of just `js`. This should make the test errors detected on CI disappear.
2. The command to run [unit tests](https://github.com/mozilla-rally/rally-core-addon/blob/4ddab3db11663d8cd80cd9bf1e0821fadc1764df/package.json#L17) must be changed to look for `mjs` files

2021-02-19 10:01 UTC, Dexterp37 commented on core-addon/background.js
> +window.browser = browser;
```suggestion
import "webextension-polyfill";
```

2021-02-19 10:01 UTC, Dexterp37 commented on core-addon/content-script.js
> +window.browser = browser;
```suggestion
import "webextension-polyfill";
```

2021-02-19 16:07 UTC, Sarthak-Dayal commented
Hey @Dexterp37! I will work on the required changes right now. Thank you for your review.

2021-02-19 21:39 UTC, Sarthak-Dayal commented
I fixed a few issues (will push those changes soon), but one of the main problems I am having is with `hooks.mjs` not recognizing `sinon-chrome/extensions` as a valid import. @Dexterp37 Would you be able to help me with this?

2021-02-22 13:38 UTC, Dexterp37 requested changes
Thanks again for your contribution! I left a few comments below. In addition to these, note that we need to export classes for them to be importable. This means, for example, that we need to replace `module.exports = class ...` with `export default class ...` in our code, otherwise compilation will break.

You can test this by reverting the renaming of `hooks.mjs` and then issuing `npm run test-addon`.

2021-02-22 13:38 UTC, Dexterp37 commented on core-addon/background.js
> +/**
Would you kindly revert the changes to the copyright notice here? :-)

2021-02-22 13:38 UTC, Dexterp37 commented on core-addon/background.js
> -    disableRemoteSettings: __DISABLE_REMOTE_SETTINGS__,
Would you kindly revert these changes? :)

2021-02-22 13:38 UTC, Dexterp37 commented on tests/hooks.mjs
> + */
Would you kindly revert these changes?

2021-02-22 13:38 UTC, Dexterp37 commented on tests/hooks.mjs
> -/* This Source Code Form is subject to the terms of the Mozilla Public
I don't think we strictly need to rename this file. We can leave it untouched.

2021-02-22 13:38 UTC, Dexterp37 commented on package.json
> +    "@types/sinon-chrome": "^2.2.10",
We don't seem to be using this dependency. Let's kindly drop it.

2021-02-22 13:38 UTC, Dexterp37 commented on package.json
> +    "mocha": "^8.3.0",
Let's not bump versions in this PR, please :)

2021-02-23 02:12 UTC, Sarthak-Dayal commented
Changing `hooks.mjs` to `hooks.js` causes the typical mocha error of "Cannot use import statement outside a module" because sinon-chrome and webextension-polyfill are being imported. The only way I see to solve this is to change it back to `.mjs` Is there anything else you had in mind? @Dexterp37

2021-02-23 09:49 UTC, Dexterp37 commented
> 
> 
> Changing `hooks.mjs` to `hooks.js` causes the typical mocha error of "Cannot use import statement outside a module" because sinon-chrome and webextension-polyfill are being imported. The only way I see to solve this is to change it back to `.mjs` Is there anything else you had in mind? @Dexterp37

You can leave the the `hooks.js` file unmodified, without migrating it to ES6 modules for now.

2021-03-08 11:41 UTC, Dexterp37 commented
Hey @Sarthak-Dayal ! Are you still considering working on this? :)

2021-03-08 17:27 UTC, Sarthak-Dayal commented
Hey @Dexterp37 ! Yes, I apologise that i wasn't able to contribute much. I got really busy with other things. I will certainly try to get the PR completely ready this week.

2021-03-09 08:24 UTC, Dexterp37 commented
> 
> 
> Hey @Dexterp37 ! Yes, I apologise that i wasn't able to contribute much. I got really busy with other things. I will certainly try to get the PR completely ready this week.

No need to apoligise, don't worry! No pressure, I just wanted to make sure you were still interested in doing this :-)

2021-03-18 15:48 UTC, Dexterp37 commented
@Sarthak-Dayal apologies :-( This was bumped in priority due to a dependency and we need to work on this, so I'm finishing it up. If you are still interested in contributing, would you consider [this bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1695884)?

2021-03-18 21:29 UTC, Dexterp37 commented
Closed in favour of #507

2021-03-18 21:29 UTC, closed without merging